[package]
name = "ntex-identity"
version = "4.0.0-beta.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Identity service for ntex web framework."
readme = "README.md"
keywords = ["http", "web", "async"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex-extras.git"
documentation = "https://docs.rs/ntex-identity/"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.95"

[lib]
name = "ntex_identity"
path = "src/lib.rs"

[features]
default = ["cookie-policy"]

cookie-policy = ["cookie/secure", "ntex/cookie"]

[dependencies]
ntex = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
cookie = { workspace = true, features = ["private"] }
time = { workspace = true, default-features = false, features = ["std"] }
thiserror = { workspace = true }