[package]
name = "ntex-cors"
version = "4.0.0-beta.2"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Cross-origin resource sharing (CORS) for ntex applications."
readme = "README.md"
keywords = ["ntex", "web"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex-extras.git"
documentation = "https://docs.rs/ntex-cors/"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.95"

[lib]
name = "ntex_cors"
path = "src/lib.rs"

[dependencies]
ntex = { workspace = true }
derive_more = { workspace = true, features = ["from", "display"] }
futures = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ntex = { workspace = true, features=["neon"] }
