[package]
name = "ntex-multipart"
version = "4.0.0-beta.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Multipart support for ntex web framework."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "ntex"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex-extras.git"
documentation = "https://docs.rs/ntex-multipart/"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.95"

[lib]
name = "ntex_multipart"
path = "src/lib.rs"

[features]
form = ["derive", "serde", "serde_json", "serde_plain"]
derive = ["ntex-multipart-derive"]

[dependencies]
ntex = { workspace = true }
ntex-files = { workspace = true }
ntex-multipart-derive = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["deref", "deref_mut", "error", "from"] }
httparse = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
mime = { workspace = true }
twoway = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde_plain = { workspace = true, optional = true }
tempfile = { workspace = true }

[dev-dependencies]
ntex = { workspace = true, features=["tokio"] }
futures-test = { workspace = true }
